version: '3.8'
services:
 app:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
      - "3005:3000"
   env_file:
     - .env
 dynamodb:
   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
   image: "amazon/dynamodb-local:latest"
   environment:
      - DYNAMODB_PORT=8000
   env_file:
     - .env
   ports:
     - "8000:8000"
   volumes:
     - dynamodb:/home/dynamodblocal/data
   working_dir: /home/dynamodblocal

volumes:
    dynamodb:
